### PR TITLE
:construction: Automatic compilation of raw efabless PDKs into a gdsfactory-compatible PDK

### PR DESCRIPTION
**Pull request by daquintero**
Related to https://github.com/gdsfactory/gplugins/issues/390, and inspired by the ehtos of making this gdsfactory library mapped to the updated raw efabless pdks https://github.com/efabless/skywater-pdk-libs-sky130_fd_pr, https://github.com/gdsfactory/skywater130/pull/67 

I think the ideal interim solution in relation to having an updated gdsfacotry-efabless PDK eg https://github.com/efabless/skywater-pdk-libs-sky130_fd_pr would be to have the fixed as a submodule and gdsfactory recursing though them to get the cell declarations. Ultimately, this is an application repository that builds onto the existing pdks. As such, and given that most users are using volare etc to install the PDKs, I'm not sure this is the most straightforward strategy on including the gdscells onto the package. WHat we can do, rather than pip installing possibly, would be to include the source PDK repositories and simply add the gdswrapper functionality on top of that. However, this comes at a packaging complexity problem.

Thought to open the draft PR since it's starting to work per the basic example I'm working on, and in case there's any feedback before I start consolidating the files and structure.

Will rebase when I cleanup the commits and code.

### CODE REVIEW

**Comment by daquintero** [comment]
@joamatab ready for review I think, however I am not sure how you want to manage the component setting updates for those tests to pass with the new structure. Lmk to update accordingly. I suspect in the pyproject.toml the submodule dependencies will have to be added to we can upload this to pypi, but since you're the package manager keen to see what you think before implementing that?

**Review by joamatab — APPROVED** [review]
Looks great! thank you Dario!

**Comment by daquintero** [comment]
Sounds good, then I'll keep on this direction! I'll update the package build to make sure it can still upload to pypi and get the tests to pass and then I believe it'll be ready to merge - and add other functionality on another PR. 

Also, if you want someone else to more constantly manage this repo happy to be a repo collaborator and on top of maintaining it - maybe let's see how much more functionality I'll add here too.

**Comment by daquintero** [comment]
Hi @joamatab , good news :tada:, I think it is ready for at least a minor release (could even be major). I have fixed the build issues, and pip installed the built-package locally successfully, tests are passing on the actions, and seems to be working pretty slickly locally. 

I don't think there's another sky130nm package that can get installed so easily and completely by pip, so quite exciting to make this more accessible especially using gdsfactory. Further upgrades to come :rocket: with more spice integration.

**Comment by joamatab** [comment]
amazing job! thank you Dario, lets merge and try to release to see if this works

**Pull request merged**
